"use client";

import {useEffect, useRef, useState} from "react";
import mapboxgl, {type Map as MapboxMap, type Marker} from "mapbox-gl";
import "mapbox-gl/dist/mapbox-gl.css";
import {Input} from "@/components/ui/input";
import {Button} from "@/components/ui/button";
import {Trash2} from "lucide-react";

export type PickupPoint = {id:string;name:string;address:string;longitude:number;latitude:number};
type Suggestion = {id:string;place_name:string;center:[number,number]};

export default function MapboxPickupSelector({points,onChange,destination}:{points:PickupPoint[];onChange:(points:PickupPoint[])=>void;destination:string}) {
 const mapNode=useRef<HTMLDivElement>(null);const map=useRef<MapboxMap|null>(null);const markers=useRef<Marker[]>([]);const pointsRef=useRef(points);const onChangeRef=useRef(onChange);pointsRef.current=points;onChangeRef.current=onChange;const [query,setQuery]=useState("");const [suggestions,setSuggestions]=useState<Suggestion[]>([]);const [searching,setSearching]=useState(false);const token=process.env.NEXT_PUBLIC_MAPBOX_TOKEN;
 const centers:Record<string,[number,number]>={Agafay:[-8.14,31.45],Zagora:[-5.84,30.33],Merzouga:[-4.01,31.1],Marrakech:[-7.9811,31.6295],Saidia:[-2.28,35.08],Other:[-7.9811,31.6295]};
 useEffect(()=>{if(!mapNode.current||!token)return;mapboxgl.accessToken=token;const instance=new mapboxgl.Map({container:mapNode.current,style:"mapbox://styles/mapbox/streets-v12",center:centers[destination]||centers.Marrakech,zoom:destination==="Marrakech"?11:9});instance.addControl(new mapboxgl.NavigationControl({showCompass:false}),"top-right");instance.on("click",event=>{const coordinates=event.lngLat.toArray();const current=pointsRef.current;onChangeRef.current([...current,{id:crypto.randomUUID(),name:`Pickup point ${current.length+1}`,address:"Selected on map",longitude:coordinates[0],latitude:coordinates[1]}]);});map.current=instance;return()=>{markers.current.forEach(marker=>marker.remove());markers.current=[];instance.remove();map.current=null;};},[token]);
 useEffect(()=>{if(map.current)map.current.flyTo({center:centers[destination]||centers.Marrakech,zoom:destination==="Marrakech"?11:9});},[destination]);
 useEffect(()=>{if(!map.current)return;markers.current.forEach(marker=>marker.remove());markers.current=points.map((point,index)=>new mapboxgl.Marker({color:"#67B500"}).setLngLat([point.longitude,point.latitude]).setPopup(new mapboxgl.Popup({offset:18}).setText(point.name||`Pickup point ${index+1}`)).addTo(map.current!));},[points]);
 async function search(){if(!token||!query.trim())return;setSearching(true);try{const url=new URL(`https://api.mapbox.com/geocoding/v5/mapbox.places/${encodeURIComponent(query)}.json`);url.searchParams.set("access_token",token);url.searchParams.set("country","ma");url.searchParams.set("language","en");url.searchParams.set("limit","5");if(destination&&destination!=="Other")url.searchParams.set("proximity",centers[destination].join(","));const response=await fetch(url);const result=await response.json();setSuggestions(result.features??[]);}catch{setSuggestions([]);}finally{setSearching(false);}}
 function choose(item:Suggestion){const [longitude,latitude]=item.center;onChange([...points,{id:crypto.randomUUID(),name:item.place_name.split(",")[0],address:item.place_name,longitude,latitude}]);map.current?.flyTo({center:[longitude,latitude],zoom:14});setQuery("");setSuggestions([]);}
 function updatePoint(index:number,key:"name"|"address",value:string){onChange(points.map((point,i)=>i===index?{...point,[key]:value}:point));}
 return <section className="grid gap-3 rounded border border-[#e0e0e0] p-4"><div><h3 className="text-sm font-semibold text-[#222]">Pickup locations and service area</h3><p className="mt-1 text-xs text-[#777]">Search for a place or click the map to add multiple pickup points. Each pin is part of your pickup coverage.</p></div>{token?<><div className="flex gap-2"><Input value={query} onChange={event=>setQuery(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"){event.preventDefault();void search();}}} placeholder="Search address or landmark in Morocco"/><Button type="button" variant="outline" onClick={()=>void search()} disabled={searching}>{searching?"Searching…":"Search"}</Button></div>{suggestions.length>0&&<div className="grid gap-1 rounded border bg-white p-1">{suggestions.map(item=><button type="button" key={item.id} onClick={()=>choose(item)} className="rounded px-3 py-2 text-left text-sm hover:bg-[#f4f8f1]">{item.place_name}</button>)}</div>}<div ref={mapNode} className="h-72 overflow-hidden rounded-sm border bg-[#f3f5f2]" aria-label="Mapbox pickup area selector"/><p className="text-[11px] text-[#777]">Click any point on the map to add it to the pickup list below.</p></>:<p role="alert" className="rounded bg-amber-50 p-3 text-sm text-amber-900">Mapbox is unavailable. Add a NEXT_PUBLIC_MAPBOX_TOKEN to enable map selection.</p>}
 {points.length>0&&<div className="grid gap-2">{points.map((point,index)=><article key={point.id} className="grid gap-2 rounded border bg-[#fafafa] p-3 sm:grid-cols-[1fr_1fr_auto]"><Input aria-label={`Pickup point ${index+1} name`} value={point.name} onChange={event=>updatePoint(index,"name",event.target.value)} placeholder={`Pickup point ${index+1} name`}/><Input aria-label={`Pickup point ${index+1} address`} value={point.address} onChange={event=>updatePoint(index,"address",event.target.value)} placeholder="Full address"/><Button type="button" variant="outline" size="icon" aria-label={`Remove pickup point ${index+1}`} onClick={()=>onChange(points.filter((_,i)=>i!==index))}><Trash2 className="h-4 w-4 text-red-600"/></Button><p className="text-[11px] text-[#777] sm:col-span-3">{point.latitude.toFixed(5)}, {point.longitude.toFixed(5)}</p></article>)}</div>}
 </section>;
}
