"use client";

import {useEffect,useState} from "react";
import {ArrowLeft} from "lucide-react";
import {Button} from "@/components/ui/button";

type PreviewData={title?:string;summary?:string;paragraphs?:string[];highlights?:string[];destination?:string;destinationOther?:string;durationValue?:string;durationUnit?:"days"|"hours";prices?:Record<string,string>;childPrices?:Record<string,string>;recommendedTier?:string;pricingModel?:string;media?:{id:string;name:string;alt:string;caption:string}[];coverId?:string;included?:string[];faq?:{id:string;question:string;answer:string}[]};
const KEY="partner-product-drafts-v2";
export default function ProductPreview({productId}:{productId:string}){
 const [data,setData]=useState<PreviewData|null>(null);const [cover,setCover]=useState("");
 useEffect(()=>{let draft:PreviewData|null=null;try{draft=(JSON.parse(localStorage.getItem(KEY)||"{}") as Record<string,PreviewData>)[productId]??null;}catch{}setData(draft);if(draft?.coverId){const req=indexedDB.open("partner-product-media-v1",1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains("images"))req.result.createObjectStore("images");};req.onsuccess=()=>{const db=req.result;const get=db.transaction("images").objectStore("images").get(`${productId}:${draft!.coverId}`);get.onsuccess=()=>{if(get.result instanceof Blob)setCover(URL.createObjectURL(get.result));db.close();};};}return()=>{if(cover.startsWith("blob:"))URL.revokeObjectURL(cover);};},[productId]);
 if(!data)return <div className="rounded border bg-white p-8"><p className="font-semibold">No saved product preview found.</p><Button className="mt-4" onClick={()=>history.back()}><ArrowLeft className="mr-2 h-4 w-4"/>Back to editor</Button></div>;
 const destination=data.destination==="Other"?data.destinationOther:data.destination;const duration=data.durationValue?`${data.durationValue} ${data.durationUnit||"hours"}`:"";const price=data.pricingModel==="quote"?"Request a quote":`${data.prices?.[data.recommendedTier||"standard"]||"—"} €`;
 return <main className="mx-auto max-w-5xl overflow-hidden rounded border bg-white shadow-sm"><div className="relative h-64 bg-[#e9eee7] md:h-80">{cover?<img src={cover} alt={data.media?.find(m=>m.id===data.coverId)?.alt||""} className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center text-[#777]">Product cover photo</div>}</div><div className="p-5 md:p-8"><p className="text-xs text-[#777]">{destination} · {duration}</p><div className="mt-2 flex flex-wrap items-start justify-between gap-4"><h1 className="text-3xl font-bold text-[#222]">{data.title||"Untitled product"}</h1><div className="text-right"><p className="text-xs text-[#777]">From</p><p className="text-3xl font-bold text-[#4CAF50]">{price}</p>{data.pricingModel!=="quote"&&<p className="text-sm text-[#555]">Adult · {data.childPrices?.[data.recommendedTier||"standard"]||"—"} € child</p>}</div></div><p className="mt-4 text-[#444]">{data.summary}</p><section className="mt-8">{data.paragraphs?.filter(Boolean).map((p,i)=><p key={i} className="mt-3 leading-7 text-[#444]">{p}</p>)}</section><div className="mt-6 flex flex-wrap gap-2">{data.highlights?.filter(Boolean).map((item,i)=><span key={i} className="rounded-full border border-[#67B500] px-3 py-1 text-xs text-gray-900">{item}</span>)}</div>{data.included?.some(Boolean)&&<section className="mt-8"><h2 className="text-xl font-bold">Included</h2><ul className="mt-3 grid gap-2 md:grid-cols-2">{data.included.filter(Boolean).map((item,i)=><li key={i} className="flex items-center gap-2 text-sm"><span className="text-gray-900">✓</span>{item}</li>)}</ul></section>}{data.faq?.some(f=>f.question)&&<section className="mt-8"><h2 className="text-xl font-bold">Frequently asked questions</h2>{data.faq.filter(f=>f.question).map(f=><details key={f.id} className="border-b py-3"><summary className="cursor-pointer font-semibold">{f.question}</summary><p className="mt-2 text-sm text-[#555]">{f.answer}</p></details>)}</section>}<Button className="mt-8" onClick={()=>history.back()}><ArrowLeft className="mr-2 h-4 w-4"/>Back to editor</Button></div></main>;
}
